apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cert-manager
  - ../ingress-nginx
  - ../monitoring
  - ../security
  - ../backup
  - ../storage

commonLabels:
  app.kubernetes.io/part-of: infrastructure
  managed-by: fluxcd

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node-type: system 