apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gotify
  namespace: observability
  labels:
    app.kubernetes.io/name: gotify
    app.kubernetes.io/component: notifications
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate

    image:
      repository: gotify/server
      tag: 2.4.0

    env:
      TZ: UTC
      GOTIFY_DEFAULTUSER_NAME: admin
      GOTIFY_DEFAULTUSER_PASS: "admin123"  # Change this in production
      GOTIFY_REGISTRATION: "false"
      GOTIFY_UPLOADSIZE: 32mb
      GOTIFY_PASSSTRENGTH: 10

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 32m
        hosts:
          - host: &host "gotify.local"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        mountPath: /app/data

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
