---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: on-call-secrets
  namespace: observability
  labels:
    app.kubernetes.io/name: on-call-rotation
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: on-call-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        pagerduty-api-key: "{{ .pagerduty_api_key }}"
        slack-bot-token: "{{ .slack_bot_token }}"
        oncall-webhook-secret: "{{ .oncall_webhook_secret }}"
  data:
  - secretKey: pagerduty_api_key
    remoteRef:
      key: on-call-integration
      property: pagerduty_api_key
  - secretKey: slack_bot_token
    remoteRef:
      key: on-call-integration
      property: slack_bot_token
  - secretKey: oncall_webhook_secret
    remoteRef:
      key: on-call-integration
      property: webhook_secret 