apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-updater
  namespace: observability
  labels:
    app.kubernetes.io/name: status-updater
    app.kubernetes.io/component: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: status-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: status-updater
        app.kubernetes.io/component: automation
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: status-updater
        image: python:3.11-slim
        command:
        - python
        - /app/status-updater.py
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus.observability:9090"
        - name: STATUS_PAGE_URL
          value: "http://status-page.observability"
        - name: STATUS_PAGE_TOKEN
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: webhook-secret
        volumeMounts:
        - name: config
          mountPath: /app
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: status-page-config
          items:
          - key: status-updater.py
            path: status-updater.py
            mode: 0755
      restartPolicy: Always 