apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page
  namespace: observability
  labels:
    app.kubernetes.io/name: status-page
    app.kubernetes.io/component: public-status
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: status-page
  template:
    metadata:
      labels:
        app.kubernetes.io/name: status-page
        app.kubernetes.io/component: public-status
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: status-page
        image: ghcr.io/cachethq/cachet:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: APP_URL
          value: "https://status.samcloud.online"
        - name: APP_TIMEZONE
          value: "UTC"
        - name: DB_DRIVER
          value: "pgsql"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: db-host
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: db-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: db-password
        - name: CACHE_DRIVER
          value: "redis"
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: redis-host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: redis-password
        - name: MAIL_DRIVER
          value: "smtp"
        - name: MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: smtp-host
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: smtp-username
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: status-page-secrets
              key: smtp-password
        - name: MAIL_ADDRESS
          value: "status@samcloud.online"
        - name: MAIL_NAME
          value: "SamCloud Status"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL 