apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: status-page-secrets
  namespace: observability
  labels:
    app.kubernetes.io/name: status-page
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: status-page-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        db-host: "{{ .db_host }}"
        db-name: "{{ .db_name }}"
        db-username: "{{ .db_username }}"
        db-password: "{{ .db_password }}"
        redis-host: "{{ .redis_host }}"
        redis-password: "{{ .redis_password }}"
        smtp-host: "{{ .smtp_host }}"
        smtp-username: "{{ .smtp_username }}"
        smtp-password: "{{ .smtp_password }}"
        app-key: "{{ .app_key }}"
        webhook-secret: "{{ .webhook_secret }}"
  data:
  - secretKey: db_host
    remoteRef:
      key: status-page-database
      property: host
  - secretKey: db_name
    remoteRef:
      key: status-page-database
      property: database
  - secretKey: db_username
    remoteRef:
      key: status-page-database
      property: username
  - secretKey: db_password
    remoteRef:
      key: status-page-database
      property: password
  - secretKey: redis_host
    remoteRef:
      key: status-page-redis
      property: host
  - secretKey: redis_password
    remoteRef:
      key: status-page-redis
      property: password
  - secretKey: smtp_host
    remoteRef:
      key: status-page-smtp
      property: host
  - secretKey: smtp_username
    remoteRef:
      key: status-page-smtp
      property: username
  - secretKey: smtp_password
    remoteRef:
      key: status-page-smtp
      property: password
  - secretKey: app_key
    remoteRef:
      key: status-page-app
      property: key
  - secretKey: webhook_secret
    remoteRef:
      key: status-page-app
      property: webhook_secret 