---
creation_rules:
  - path_regex: .*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1pn9yaaq087hehhytd4kkjptah8zay6e3xehahzdl06h7rrx9kp5qj3z4wy"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1pn9yaaq087hehhytd4kkjptah8zay6e3xehahzdl06h7rrx9kp5qj3z4wy"
stores:
  yaml:
    indent: 2
