---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: graphite-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: graphite-exporter
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-graphite-exporter
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
          keepHistory: false
  dependsOn: []
  values:
    graphite:
      port: 9109
      mappingConfig: |
        mappings:
        - match: "*.*.*.*.*.*.*.*.*.*.*.*.stats.counter.*"
          name: "stats_count"
          labels:
            app: "$1"
            type: "counter"
        - match: "*.*.*.*.*.*.*.*.*.*.*.*.stats.gauge.*"
          name: "stats_gauge"
          labels:
            app: "$1"
            type: "gauge"
        - match: "*.*.*.*.*.*.*.*.*.*.*.*.stats.timer.*"
          name: "stats_timer"
          labels:
            app: "$1"
            type: "timer"

    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    controllers:
      graphite-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            args:
              - "--graphite.mapping-config=/tmp/graphite_mapping.conf"
              - "--graphite.listen-address=:2003"
              - "--log.level=debug"
            image:
              repository: docker.io/prom/graphite-exporter
              tag: v0.16.0@sha256:e54bca6645ea8a9e8c52312a8540de98ad08819d38476c021d77a0eae75bc797
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 10m
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
        replicas: 2
        strategy: RollingUpdate
    persistence:
      graphite-mapping:
        type: configMap
        name: graphite-exporter-config
        globalMounts:
          - path: /tmp/graphite_mapping.conf
            subPath: graphite_mapping.conf
            readOnly: true
    service:
      app:
        controller: graphite-exporter
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.8.109
        ports:
          graphite-tcp:
            protocol: TCP
            port: 2003
            primary: true
          graphite-udp:
            protocol: UDP
            port: 2003
          metrics:
            port: 9108
