#---
## Source: api/templates/virtual_service.yaml
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: wazuh-admin-certificate
#  namespace: wazuh-system
#spec:
#  issuerRef:
#    group: cert-manager.io
#    kind: Issuer
#    name: wazuh-issuer
#  secretName: wazuh-admin-tls
#  commonName: admin
#  dnsNames:
#    - "admin"
#  usages:
#    - "signing"
#    - "key encipherment"
#    - "server auth"
#    - "client auth"
#  duration: 2160h
#  renewBefore: 360h
#  isCA: false
#  privateKey:
#    algorithm: RSA
#    encoding: PKCS1
#    size: 2048
#    rotationPolicy: Always

# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-admin-certificate
  namespace: security
  labels:
    app.kubernetes.io/name: wazuh
    app.kubernetes.io/component: certificates
    app.kubernetes.io/part-of: wazuh
spec:
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: wazuh-issuer
  secretName: wazuh-admin-tls
  commonName: "admin"
  dnsNames:
    - "admin"
    - "admin.security"
    - "admin.security.svc"
    - "admin.security.svc.cluster.local"
  usages:
    - "signing"
    - "key encipherment"
    - "server auth"
    - "client auth"
    - "digital signature"
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
    rotationPolicy: Always
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: wazuh-keystore-password
        key: password
  subject:
    organizations:
      - "Wazuh, Inc."
    organizationalUnits:
      - "Security"
    countries:
      - "US"
    localities:
      - "San Francisco"
    provinces:
      - "California"