apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.47.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    mode: deployment
    replicaCount: 1

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s

    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

      processors:
        batch:
          timeout: 10s
          send_batch_size: 1024
        memory_limiter:
          check_interval: 5s
          limit_mib: 200
        resourcedetection:
          detectors: [env, system]
          timeout: 5s

      exporters:
        prometheus:
          endpoint: 0.0.0.0:8889
        logging:
          verbosity: normal

      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [prometheus]
          traces:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [logging]

    ports:
      - name: otlp-grpc
        port: 4317
        protocol: TCP
        targetPort: 4317
      - name: otlp-http
        port: 4318
        protocol: TCP
        targetPort: 4318
      - name: metrics
        port: 8889
        protocol: TCP
        targetPort: 8889