---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mimir
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mimir
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MINIO_ACCESS_KEY: "{{ .minio_access_key }}"
        MINIO_SECRET_KEY: "{{ .minio_secret_key }}"
  dataFrom:
  - extract:
      key: mimir
  refreshInterval: 15m