---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: observability
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: mimir-distributed
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    mimir:
      structuredConfig:
        common:
          storage:
            backend: filesystem
        limits:
          max_label_names_per_series: 30
          max_global_series_per_user: 100000
          max_global_series_per_metric: 10000
          ingestion_rate: 10000
          ingestion_burst_size: 20000
        blocks_storage:
          backend: filesystem
          filesystem:
            dir: /data/blocks
          bucket_store:
            sync_interval: 5m
          tsdb:
            retention_period: 7d
            ship_interval: 1m
        compactor:
          data_dir: /data/compactor
          sharding_ring:
            replication_factor: 1
        distributor:
          ring:
            replication_factor: 1
        ingester:
          ring:
            replication_factor: 1
          lifecycler:
            join_after: 0s
            final_sleep: 0s
            min_ready_duration: 0s
        ruler:
          enable_api: true
          ring:
            replication_factor: 1
        ruler_storage:
          backend: filesystem
          filesystem:
            dir: /data/ruler

    gateway:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    distributor:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    ingester:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      persistence:
        size: 10Gi

    store_gateway:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      persistence:
        size: 10Gi

    compactor:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      persistence:
        size: 10Gi

    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s

    alertmanager:
      enabled: false

    test:
      enabled: false

    persistence:
      enabled: true
      size: 10Gi

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi

    ingress:
      enabled: true
      hosts:
        - host: mimir.local
          paths:
            - path: /
              pathType: Prefix