---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./prometheusrule.yaml
  - ./networkpolicy.yaml
  - ./servicemonitor.yaml