apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: observability
  labels:
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/component: log-collector
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: vector
      version: 0.28.1
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    role: Agent
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false
      sources:
        kubernetes_logs:
          type: kubernetes_logs
          pod_annotation_fields:
            container_image: container_image
            container_name: container_name
            pod_labels: pod_labels
            pod_name: pod_name
            namespace: namespace
      transforms:
        remap_kubernetes:
          type: remap
          inputs: [kubernetes_logs]
          source: |
            structured = parse_json!(.message) ?? .message
            . = merge(., structured)
            .timestamp = parse_timestamp!(.timestamp, format: "%+")
      sinks:
        loki:
          type: loki
          inputs: [remap_kubernetes]
          endpoint: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push
          encoding:
            codec: json
          labels:
            namespace: '{{ namespace }}'
            pod: '{{ pod_name }}'
            container: '{{ container_name }}'
          out_of_order_action: accept
          remove_timestamp: false
          healthcheck:
            enabled: true

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s

    securityContext:
      privileged: true

    tolerations:
      - effect: NoSchedule
        operator: Exists

    rbac:
      create: true

    persistence:
      enabled: true
      size: 10Gi