---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: blackbox-exporter
  namespace: flux-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.1.0
  url: oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_status_codes: [200]
            method: GET
        http_post_2xx:
          prober: http
          timeout: 5s
          http:
            method: POST
            valid_status_codes: [200]
        tcp_connect:
          prober: tcp
          timeout: 5s
        icmp:
          prober: icmp
          timeout: 5s
          icmp:
            preferred_ip_protocol: ip4

    serviceMonitor:
      enabled: true
      defaults:
        interval: 30s
        scrapeTimeout: 10s
      targets:
        - name: kubernetes-api
          url: https://kubernetes.default.svc
          module: http_2xx
        - name: ingress-nginx
          url: http://ingress-nginx-controller.ingress-nginx.svc
          module: http_2xx

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
