apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: security-alerts
  namespace: observability
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: security.alerts
      rules:
        # Critical Vulnerability Alerts
        - alert: CriticalVulnerabilitiesDetected
          expr: security:vulnerabilities:critical_high:total > 5
          for: 1h
          labels:
            severity: critical
            category: security
            team: security
            slo: vulnerability_management
          annotations:
            summary: High number of critical/high vulnerabilities detected
            description: |
              There are {{ $value }} critical/high vulnerabilities in the environment
              Affected components:
              {{range query "security:vulnerabilities:critical_high:total"}}
              - Namespace: {{.Labels.namespace}}, Container: {{.Labels.container}}, Image: {{.Labels.image}}
              {{end}}
            runbook_url: https://runbooks.samcloud.online/security/vulnerabilities
            dashboard_url: https://grafana.samcloud.online/d/security-scan-results
            playbook_url: https://playbooks.samcloud.online/security/vulnerability-response

        # Scan Failure Alerts
        - alert: SecurityScanFailures
          expr: security:scan:failures:24h > 2
          for: 30m
          labels:
            severity: warning
            category: security
            team: security
            slo: scan_reliability
          annotations:
            summary: Multiple security scan failures detected
            description: |
              {{ $value }} security scans have failed in the last 24 hours
              Failed jobs:
              {{range query "security:scan:failures:24h"}}
              - Job: {{.Labels.job_name}}
              {{end}}
            runbook_url: https://runbooks.samcloud.online/security/scan-failures
            dashboard_url: https://grafana.samcloud.online/d/security-scan-results
            playbook_url: https://playbooks.samcloud.online/security/scan-failure-response

        # Compliance Alerts
        - alert: ComplianceScoreDegraded
          expr: security:compliance:score < 85
          for: 6h
          labels:
            severity: warning
            category: security
            team: security
            slo: compliance
          annotations:
            summary: Security compliance score has degraded
            description: |
              Overall compliance score is {{ $value }}%
              Component scores:
              {{range query "security:kubescape:compliance_score"}}
              - Kubescape: {{.Value}}%
              {{end}}
              {{range query "security:checkov:compliance_score"}}
              - Checkov: {{.Value}}%
              {{end}}
            runbook_url: https://runbooks.samcloud.online/security/compliance
            dashboard_url: https://grafana.samcloud.online/d/security-scan-results
            playbook_url: https://playbooks.samcloud.online/security/compliance-response

        # SLO Alerts
        - alert: SecurityScanSLOBreach
          expr: security:slo:scan_success_rate < 99.9
          for: 24h
          labels:
            severity: critical
            category: security
            team: sre
            slo: scan_reliability
          annotations:
            summary: Security scan success rate SLO breach
            description: Security scan success rate is {{ $value }}%, below target SLO of 99.9%
            runbook_url: https://runbooks.samcloud.online/slo/security-scans
            dashboard_url: https://grafana.samcloud.online/d/security-scan-results
            playbook_url: https://playbooks.samcloud.online/slo/breach-response

        # Secrets Detection Alert
        - alert: SecretsDetected
          expr: security:secrets:detected:total > 0
          for: 5m
          labels:
            severity: critical
            category: security
            team: security
          annotations:
            summary: Secrets detected in codebase
            description: "{{ $value }} potential secrets detected in the codebase"
            runbook_url: https://runbooks.samcloud.online/security/secrets
            dashboard_url: https://grafana.samcloud.online/d/security-scan-results
            playbook_url: https://playbooks.samcloud.online/security/secret-exposure-response

        # SBOM Alert
        - alert: CriticalDependencyVulnerability
          expr: security:sbom:vulnerabilities:total{severity="CRITICAL"} > 0
          for: 1h
          labels:
            severity: critical
            category: security
            team: security
          annotations:
            summary: Critical vulnerabilities in dependencies
            description: |
              {{ $value }} critical vulnerabilities found in dependencies
              Affected namespaces:
              {{range query "security:sbom:vulnerabilities:total{severity='CRITICAL'}"}}
              - Namespace: {{.Labels.namespace}}
              {{end}}
            runbook_url: https://runbooks.samcloud.online/security/dependencies
            dashboard_url: https://grafana.samcloud.online/d/security-scan-results
            playbook_url: https://playbooks.samcloud.online/security/dependency-vulnerability-response