---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-api-management
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: api-management
    app.kubernetes.io/part-of: security
data:
  api-management.yaml: |
    api:
      version: v1
      rate_limiting:
        enabled: true
        requests_per_second: 100
        burst: 200

      authentication:
        methods:
          - oauth2
          - openid-connect
          - api-key

      authorization:
        enabled: true
        default_policy: deny

      monitoring:
        metrics:
          enabled: true
          path: /metrics
        health:
          enabled: true
          path: /health

      security:
        tls:
          enabled: true
          min_version: "1.2"
        cors:
          enabled: true
          allowed_origins:
            - "https://*.samcloud.online"

  api-gateway-config.yaml: |
    # API Gateway Configuration
    api_gateway:
      enabled: true
      provider: "gravitee"  
      version: "4.0"

      # Global API policies
      global_policies:
        - name: "rate-limiting"
          enabled: true
          config:
            requests_per_minute: 1000
            requests_per_hour: 10000
            requests_per_day: 100000
            burst_limit: 50

        - name: "request-validation"
          enabled: true
          config:
            validate_headers: true
            validate_query_params: true
            validate_request_body: true
            max_request_size: "1MB"

        - name: "response-transformation"
          enabled: true
          config:
            remove_sensitive_headers: true
            add_security_headers: true
            normalize_response_format: true

        - name: "audit-logging"
          enabled: true
          config:
            log_requests: true
            log_responses: true
            log_headers: true
            log_body: false  

        - name: "authentication"
          enabled: true
          config:
            required: true
            methods: ["bearer_token", "api_key", "oauth2"]
            fallback_to_basic: false

        - name: "authorization"
          enabled: true
          config:
            rbac_enabled: true
            attribute_based: true
            policy_enforcement: "strict"

      
      versioning:
        enabled: true
        strategy: "header"  
        default_version: "v1"
        supported_versions: ["v1", "v2"]
        deprecation_policy:
          sunset_header: true
          deprecation_notices: true
          migration_guides: true

      # Load balancing
      load_balancing:
        algorithm: "weighted_round_robin"
        health_checks:
          enabled: true
          interval: "30s"
          timeout: "5s"
          healthy_threshold: 2
          unhealthy_threshold: 3

      # Circuit breaker
      circuit_breaker:
        enabled: true
        failure_threshold: 5
        recovery_timeout: "60s"
        half_open_requests: 3

      # Caching
      caching:
        enabled: true
        provider: "redis"
        ttl: "300s"
        cache_key_strategy: "request_uri"
        vary_on_headers: ["Authorization", "X-API-Key"]

  api-analytics.yaml: |
    # API Analytics Configuration
    analytics:
      enabled: true
      real_time: true
      retention_days: 90

      # Metrics collection
      metrics:
        - name: "request_count"
          type: "counter"
          labels: ["method", "endpoint", "status_code", "client_id"]

        - name: "request_duration"
          type: "histogram"
          labels: ["method", "endpoint", "client_id"]
          buckets: [0.1, 0.5, 1.0, 2.5, 5.0, 10.0]

        - name: "request_size"
          type: "histogram"
          labels: ["method", "endpoint"]
          buckets: [100, 1000, 10000, 100000, 1000000]

        - name: "response_size"
          type: "histogram"
          labels: ["method", "endpoint"]
          buckets: [100, 1000, 10000, 100000, 1000000]

        - name: "error_rate"
          type: "gauge"
          labels: ["endpoint", "error_type"]

        - name: "client_connections"
          type: "gauge"
          labels: ["client_id", "connection_type"]

      # Business intelligence
      business_intelligence:
        enabled: true
        reports:
          - name: "api_usage_report"
            frequency: "daily"
            recipients: ["api-team@samcloud.online"]

          - name: "client_activity_report"
            frequency: "weekly"
            recipients: ["product-team@samcloud.online"]

          - name: "performance_report"
            frequency: "weekly"
            recipients: ["sre-team@samcloud.online"]

          - name: "security_report"
            frequency: "daily"
            recipients: ["security-team@samcloud.online"]

      # Alerting
      alerting:
        enabled: true
        channels: ["slack", "email", "pagerduty"]

        rules:
          - name: "high_error_rate"
            condition: "error_rate > 0.05"
            severity: "critical"

          - name: "high_latency"
            condition: "p95_latency > 2000"
            severity: "warning"

          - name: "rate_limit_exceeded"
            condition: "rate_limit_violations > 10"
            severity: "warning"

          - name: "unusual_traffic_pattern"
            condition: "traffic_anomaly_score > 0.8"
            severity: "info"

  api-security.yaml: |
    # API Security Configuration
    security:
      # Threat protection
      threat_protection:
        enabled: true

        # DDoS protection
        ddos_protection:
          enabled: true
          rate_limits:
            global: "10000/minute"
            per_client: "100/minute"
            per_endpoint: "1000/minute"
          blacklist_duration: "300s"

        # Bot protection
        bot_protection:
          enabled: true
          captcha_enabled: true
          user_agent_analysis: true
          behavior_analysis: true

        # Injection protection
        injection_protection:
          enabled: true
          sql_injection: true
          xss_protection: true
          command_injection: true
          path_traversal: true

        # Content validation
        content_validation:
          enabled: true
          max_request_size: "10MB"
          allowed_content_types: ["application/json", "application/x-www-form-urlencoded"]
          schema_validation: true

      # OAuth 2.0 / OpenID Connect
      oauth2:
        enabled: true
        provider: "authelia"

        # Token validation
        token_validation:
          enabled: true
          introspection_endpoint: "https://auth.samcloud.online/api/oidc/introspect"
          cache_ttl: "300s"

        # Scopes
        scopes:
          - name: "openid"
            description: "OpenID Connect identity"

          - name: "profile"
            description: "User profile information"

          - name: "email"
            description: "User email address"

          - name: "authelia.bearer"
            description: "Authelia bearer token access"

          - name: "authelia.admin"
            description: "Authelia administrative access"

      # API keys
      api_keys:
        enabled: true

        # Key management
        key_management:
          rotation_enabled: true
          rotation_interval: "90d"
          key_length: 32
          encoding: "base64url"

        # Rate limiting per key
        rate_limiting:
          enabled: true
          default_limit: "1000/hour"
          premium_limit: "10000/hour"
          enterprise_limit: "100000/hour"

        # Usage tracking
        usage_tracking:
          enabled: true
          quotas_enabled: true
          billing_enabled: true

      # mTLS
      mtls:
        enabled: true
        required_for_admin: true
        ca_certificates:
          - name: "samcloud-ca"
            path: "/etc/ssl/certs/samcloud-ca.crt"
          - name: "client-ca"
            path: "/etc/ssl/certs/client-ca.crt"

  developer-portal.yaml: |
    # Developer Portal Configuration
    developer_portal:
      enabled: true

      # Portal settings
      settings:
        title: "Authelia API Portal"
        description: "Authentication and authorization APIs"
        contact_email: "api-support@samcloud.online"
        terms_of_service: "https://samcloud.online/terms"
        privacy_policy: "https://samcloud.online/privacy"

      # API documentation
      documentation:
        enabled: true
        format: "openapi"
        interactive_docs: true
        code_samples: true

        # API specifications
        apis:
          - name: "Authentication API"
            version: "v1"
            description: "User authentication and session management"
            spec_url: "/api/v1/auth/openapi.json"

          - name: "Authorization API"
            version: "v1"
            description: "Access control and permissions"
            spec_url: "/api/v1/authz/openapi.json"

          - name: "User Management API"
            version: "v1"
            description: "User profile and settings management"
            spec_url: "/api/v1/users/openapi.json"

          - name: "Admin API"
            version: "v1"
            description: "Administrative functions"
            spec_url: "/api/v1/admin/openapi.json"

      # Client registration
      client_registration:
        enabled: true
        approval_required: true
        auto_approval_for_internal: true

        # Application types
        application_types:
          - name: "web_application"
            description: "Server-side web applications"

          - name: "spa"
            description: "Single-page applications"

          - name: "mobile_app"
            description: "Mobile applications"

          - name: "service"
            description: "Service-to-service communication"

      # SDK generation
      sdk_generation:
        enabled: true
        languages: ["javascript", "python", "java", "go", "csharp"]

      # Testing tools
      testing_tools:
        enabled: true
        api_explorer: true
        test_console: true
        mock_server: true

      # Community features
      community:
        enabled: true
        forums: true
        support_tickets: true
        feature_requests: true 