---
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: authelia-dns-failure-test
  namespace: chaos-mesh
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: chaos-engineering
spec:
  action: error
  mode: one
  selector:
    namespaces:
      - security
    labelSelectors:
      app.kubernetes.io/name: authelia
  patterns:
    - "lldap.auth.svc.cluster.local"
    - "postgres17-rw.storage.svc.cluster.local"
    - "dragonfly.storage.svc.cluster.local"
  duration: "30s"
  scheduler:
    cron: "@every 12h" 