---
# Governance and Risk Management Configuration for Authelia
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-governance
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: compliance
    app.kubernetes.io/part-of: security
    security.samcloud.online/tier: standard
data:
  governance.yaml: |
    # Governance and Risk Management
    governance:
      # Risk management
      risk_management:
        enabled: true
        risk_appetite: "moderate"
        risk_tolerance_levels:
          critical: 0      
          high: 2          
          medium: 10       
          low: 50          

      # Control frameworks
      control_frameworks:
        enabled: true
        frameworks: ["SOC2", "ISO27001", "NIST", "GDPR", "HIPAA", "PCI-DSS"]
        control_testing_frequency: "quarterly"
        control_effectiveness_threshold: 0.95

      # Policy management
      policy_management:
        enabled: true
        policy_review_frequency: "annually"
        policy_approval_required: true
        policy_version_control: true
        policy_distribution: "automated"

      # Incident management
      incident_management:
        enabled: true
        incident_classification:
          - "security_incident"
          - "privacy_incident"
          - "operational_incident"
          - "compliance_incident"
        incident_response_time:
          critical: "15m"
          high: "1h"
          medium: "4h"
          low: "24h"
        incident_escalation_enabled: true

      # Vendor management
      vendor_management:
        enabled: true
        vendor_risk_assessment: true
        vendor_security_questionnaire: true
        vendor_contract_review: true
        vendor_monitoring: true

      # Change management
      change_management:
        enabled: true
        change_approval_required: true
        change_testing_required: true
        change_rollback_plan_required: true
        emergency_change_process: true  