---
# Data Privacy and Protection Configuration for Authelia
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-data-privacy
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: compliance
    app.kubernetes.io/part-of: security
    security.samcloud.online/tier: standard
data:
  data-privacy.yaml: |
    # Data Privacy and Protection Configuration
    privacy:
      # Personal data detection
      pii_detection:
        enabled: true
        confidence_threshold: 0.85
        patterns:
          email_addresses:
            pattern: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"
            sensitivity: "medium"
          phone_numbers:
            pattern: "\\b\\d{3}-\\d{3}-\\d{4}\\b|\\b\\(\\d{3}\\)\\s*\\d{3}-\\d{4}\\b"
            sensitivity: "medium"
          ip_addresses:
            pattern: "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b"
            sensitivity: "low"
          credit_card_numbers:
            pattern: "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3[0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\\b"
            sensitivity: "critical"
          social_security_numbers:
            pattern: "\\b\\d{3}-\\d{2}-\\d{4}\\b"
            sensitivity: "critical"
          passport_numbers:
            pattern: "\\b[A-Z]{1,2}\\d{6,9}\\b"
            sensitivity: "high"
          driver_license_numbers:
            pattern: "\\b[A-Z]{1,2}\\d{6,8}\\b"
            sensitivity: "high"
          bank_account_numbers:
            pattern: "\\b\\d{8,17}\\b"
            sensitivity: "critical"
          api_keys:
            pattern: "\\b[A-Za-z0-9]{32,}\\b"
            sensitivity: "critical"
          jwt_tokens:
            pattern: "\\beyJ[A-Za-z0-9_-]*\\.[A-Za-z0-9_-]*\\.[A-Za-z0-9_-]*\\b"
            sensitivity: "critical"

        action_by_sensitivity:
          critical: "block"     
          high: "mask"          
          medium: "alert"       
          low: "log"            

      # Data minimization
      minimization:
        enabled: true
        auto_cleanup: true
        retention_policies:
          logs: "30d"
          metrics: "90d"
          traces: "7d"
          audit: "7y"
          user_sessions: "24h"
          temporary_files: "1h"
          cache_data: "6h"

      # Anonymization
      anonymization:
        enabled: true
        methods:
          - "hash_stable"      
          - "generalization"   
          - "perturbation"     
          - "masking"          
          - "tokenization"     
        preserve_analytics: true
        anonymization_keys:
          - "user_id"
          - "session_id"
          - "ip_address"
          - "email"

      # Consent management
      consent:
        enabled: true
        default_consent: false
        explicit_consent_required: true
        consent_expiry_days: 365
        consent_categories:
          - "authentication"
          - "session_management"
          - "audit_logging"
          - "performance_monitoring"
          - "security_monitoring"

      # Right to be forgotten
      erasure:
        enabled: true
        automated: true
        verification_required: true
        retention_override: false
        erasure_methods:
          - "secure_delete"
          - "cryptographic_erasure"
          - "data_fragmentation"
        verification_period_days: 30

      # Data breach response
      breach_response:
        enabled: true
        notification_required: true
        notification_timeframe_hours: 72
        severity_levels:
          - "low"
          - "medium"
          - "high"
          - "critical"
        escalation_matrix:
          low: ["security@samcloud.online"]
          medium: ["security@samcloud.online", "compliance@samcloud.online"]
          high: ["security@samcloud.online", "compliance@samcloud.online", "legal@samcloud.online", "ciso@samcloud.online"]
          critical: ["security@samcloud.online", "compliance@samcloud.online", "legal@samcloud.online", "ciso@samcloud.online", "ceo@samcloud.online"] 