---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: authelia-resource-quota
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: cost-optimization
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
    persistentvolumeclaims: "5"
    requests.storage: 20Gi
    count/secrets: "10"
    count/configmaps: "10"
    count/services: "5"
    count/ingresses.networking.k8s.io: "2"
    count/certificates.cert-manager.io: "3"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: authelia-limit-range
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: cost-optimization
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "1"
        memory: 512Mi
      min:
        cpu: 10m
        memory: 32Mi
    - type: Pod
      max:
        cpu: "2"
        memory: 1Gi
    - type: PersistentVolumeClaim
      max:
        storage: 10Gi
      min:
        storage: 1Gi 