---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: authelia-vpa
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: cost-optimization
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authelia
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 2
  resourcePolicy:
    containerPolicies:
      - containerName: app
        minAllowed:
          cpu: 10m
          memory: 64Mi
        maxAllowed:
          cpu: 500m
          memory: 512Mi
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits
      - containerName: init-db
        mode: "Off"  