apiVersion: v1
kind: ServiceAccount
metadata:
  name: authelia-multi-region
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: multi-region
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authelia-multi-region
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: multi-region
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authelia-multi-region
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: multi-region
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authelia-multi-region
subjects:
  - kind: ServiceAccount
    name: authelia-multi-region
    namespace: security 