apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: authelia-scc
  annotations:
    kubernetes.io/description: "Security context constraints for Authelia"
    compliance.kubernetes.io/frameworks: "soc2,iso27001,nist"
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
  ranges:
    - min: 568
      max: 568
readOnlyRootFilesystem: true
runAsUser:
  type: MustRunAs
  uid: 568
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
  ranges:
    - min: 568
      max: 568
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret 