# ServiceAccount for Snapshot Operations
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authelia-snapshot-sa
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authelia-snapshot-role
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: storage
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authelia-snapshot-binding
  namespace: security
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authelia-snapshot-role
subjects:
  - kind: ServiceAccount
    name: authelia-snapshot-sa
    namespace: security 