# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
  namespace: flux-system
stringData:
  token: ENC[AES256_GCM,data:OAK70KtAqzpe3FwLPkw8ytxZszlua8sPURXRiUo8FiQr3bWQns/uHA==,iv:Tx7I17ZP8szp56G9LmJ0Iewc4qzUfrcslBwgmKLTPkE=,tag:0t2AukOX+zomqWKApebu5w==,type:str]
sops:
  age:
    - recipient: age1gv4yr3apdak04wmkzdysvnxh2m5fu2ydyg34nt8terf56n7gtpnqaqg8ql
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTekxRNnJKRWtsamJTclps
        bVZHdEtoRG5zeGhxZFdnV0FheUZ0NlRyakJFCmN5ZFVZZTVkOFFyUTJNdHFIdTFy
        UGpMY2lyL3A4ZjhjckNtNTE1KzRtaDAKLS0tIEo1Z21RcHBpUlVtdThCd05vdUlh
        Qi9LKzhTZFlFazVGRHpkdG1kUTd6TDAKpiOh/Rdo97qpHTuhsPbIzPY0ebZXNyBa
        VpFnMjmGmHdr3LS0cy8v0H28Svymx9ObMpT+rmyRhgChWczQMEA3/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-01T15:55:21Z"
  mac: ENC[AES256_GCM,data:veR0cH0O+PNTPZNKdSX66XtcCqI7xWBzr0VD734XYGTi0soiXuAA8GeF0BCwituqKCryEaxG71yyoiVUFGEE/hWbbR9C5ANmTr5AhdV2bDU+3j04KHwHelFEqJt7q0/9mgEPIGTztlCLJL0rf2t/cucIFQLGQgtTPicKeiskjs8=,iv:f8chotXJefH0WuLF9DkJ+86WB0WN3meXyfAmOr0GpZ4=,tag:QSWru9bhuy0znCNaunGOUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
