---
creation_rules:
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1gv4yr3apdak04wmkzdysvnxh2m5fu2ydyg34nt8terf56n7gtpnqaqg8ql"
stores:
  yaml:
    indent: 2
