---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GRAFANA_ADMIN_PASSWORD: "{{ .admin_password }}"
        GRAFANA_SECRET_KEY: "{{ .secret_key }}"
        DB_HOST: "{{ .db_host }}"
        DB_NAME: "{{ .db_name }}"
        DB_USER: "{{ .db_user }}"
        DB_PASSWORD: "{{ .db_password }}"
        SMTP_HOST: "{{ .smtp_host }}"
        SMTP_USER: "{{ .smtp_user }}"
        SMTP_PASSWORD: "{{ .smtp_password }}"
        CLICKHOUSE_USER: "{{ .clickhouse_user }}"
        CLICKHOUSE_PASSWORD: "{{ .clickhouse_password }}"
        POSTGRES_USER: "{{ .postgres_user }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
  dataFrom:
  - extract:
      key: grafana
  refreshInterval: 15m
