apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: visualization
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 7.0.19
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicas: 1

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s

    persistence:
      enabled: true
      size: 10Gi

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-operated:9090
            isDefault: true
            access: proxy
            editable: true
          - name: Loki
            type: loki
            url: http://loki-gateway
            access: proxy
            editable: true
          - name: Tempo
            type: tempo
            url: http://tempo:3200
            access: proxy
            editable: true
            jsonData:
              nodeGraph:
                enabled: true
              tracesToLogs:
                datasourceUid: loki
                filterByTraceID: true
                spanEndTimeShift: "500ms"
                spanStartTimeShift: "-500ms"
                tags: ['container', 'namespace', 'pod']

    grafana.ini:
      auth:
        disable_login_form: false
      auth.anonymous:
        enabled: true
        org_role: Viewer
      server:
        root_url: https://grafana.samcloud.online
      security:
        allow_embedding: true
        cookie_secure: true
      dashboards:
        min_refresh_interval: 30s
      users:
        viewers_can_edit: false

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: simple-icons:grafana
        hosts:
          - host: &host "grafana.samcloud.online"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
