apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: observability
  labels:
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/component: chaos-engineering
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: chaos-mesh
      version: 2.6.3
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllerManager:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    chaosDaemon:
      runtime: containerd
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    dashboard:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:lightning-bolt
        hosts:
          - host: &host "chaos.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    prometheus:
      monitor:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s

    webhook:
      enabled: true
      certManager:
        enabled: true

    podChaos: true
    networkChaos: true
    stressChaos: true
    timeChaos: false
    ioChaos: false
    kernelChaos: false
    DNSChaos: false

    rbac:
      create: true

    serviceAccount:
      create: true