---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: observability
  labels:
    app.kubernetes.io/name: gatus
    app.kubernetes.io/component: health-checks
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: gatus
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s

    service:
      main:
        enabled: true
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &host "health.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    config:
      metrics: true
      storage:
        type: memory
      endpoints:
        - name: core-dns
          group: dns
          url: "tcp://kube-system-coredns:53"
          interval: 1m
          conditions:
            - "connected == true"
        - name: ingress-nginx
          group: ingress
          url: "tcp://ingress-nginx-controller:80"
          interval: 1m
          conditions:
            - "connected == true"
        - name: prometheus
          group: monitoring
          url: "http://prometheus-operated:9090/-/healthy"
          interval: 1m
          conditions:
            - "[STATUS] == 200"
        - name: alertmanager
          group: monitoring
          url: "http://alertmanager-operated:9093/-/healthy"
          interval: 1m
          conditions:
            - "[STATUS] == 200"
        - name: grafana
          group: monitoring
          url: "http://grafana:80/api/health"
          interval: 1m
          conditions:
            - "[STATUS] == 200"
        - name: loki
          group: monitoring
          url: "http://loki-gateway/ready"
          interval: 1m
          conditions:
            - "[STATUS] == 200"
        - name: tempo
          group: monitoring
          url: "http://tempo:3200/ready"
          interval: 1m
          conditions:
            - "[STATUS] == 200"
