---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snmp-exporter
  namespace: flux-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 9.4.0
  url: oci://ghcr.io/prometheus-community/charts/prometheus-snmp-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snmp-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
      targets:
        - name: router
          address: 192.168.1.1
          module: if_mib
          community: public
        - name: switch
          address: 192.168.1.2
          module: if_mib
          community: public

    config:
      modules:
        if_mib:
          walk:
            - 1.3.6.1.2.1.2.2.1.1  # ifIndex
            - 1.3.6.1.2.1.2.2.1.2  # ifDescr
            - 1.3.6.1.2.1.2.2.1.3  # ifType
            - 1.3.6.1.2.1.2.2.1.5  # ifSpeed
            - 1.3.6.1.2.1.2.2.1.8  # ifOperStatus
            - 1.3.6.1.2.1.2.2.1.10 # ifInOctets
            - 1.3.6.1.2.1.2.2.1.16 # ifOutOctets
            - 1.3.6.1.2.1.2.2.1.14 # ifInErrors
            - 1.3.6.1.2.1.2.2.1.20 # ifOutErrors
          metrics:
            - name: ifOperStatus
              oid: 1.3.6.1.2.1.2.2.1.8
              type: gauge
              help: The current operational state of the interface
            - name: ifInOctets
              oid: 1.3.6.1.2.1.2.2.1.10
              type: counter
              help: The total number of octets received on the interface
            - name: ifOutOctets
              oid: 1.3.6.1.2.1.2.2.1.16
              type: counter
              help: The total number of octets transmitted out of the interface
            - name: ifInErrors
              oid: 1.3.6.1.2.1.2.2.1.14
              type: counter
              help: The number of inbound packets that contained errors
            - name: ifOutErrors
              oid: 1.3.6.1.2.1.2.2.1.20
              type: counter
              help: The number of outbound packets that could not be transmitted because of errors
