---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector-aggregator
  namespace: observability
spec:
  dependsOn:
    - name: loki
      namespace: observability
    - name: external-secrets
      namespace: security
    - name: onepassword
      namespace: security
  path: ./kubernetes/apps/observability/vector/aggregator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector-agent
  namespace: observability
spec:
  dependsOn:
    - name: vector-aggregator
      namespace: observability
  path: ./kubernetes/apps/observability/vector/agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
