---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.41.0
  url: oci://ghcr.io/grafana/helm-charts/loki
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: log-aggregation
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: 5.48.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      storage_config:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      limits_config:
        retention_period: 7d
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 15m
      chunk_store_config:
        max_look_back_period: 168h
      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h
      compactor:
        working_directory: /var/loki/boltdb-shipper-compactor
        shared_store: filesystem
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150

    monitoring:
      serviceMonitor:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false

    gateway:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    write:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      persistence:
        size: 10Gi

    read:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    backend:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      persistence:
        size: 10Gi

    test:
      enabled: false
