#ENC[AES256_GCM,data:9xYp8zI0KinkWh9aOd58vFApz260m0J/x0zLnXsWGaCOmxdGfh8V54zqo96Kos9sqisANR5YrV8+e+6h1w0wLlsHYPvfTJGybrX9koqldldtowIuwenop+R0gSmc8fU5H9645QfxKto=,iv:ZdzJGmEuc0s8PaCrFwFsJ4XW0GwjVutMDrZ9TcoBs3o=,tag:H63Ir5WPDyqVnGrUEqoJRw==,type:comment]
apiVersion: ENC[AES256_GCM,data:4TI=,iv:1tO4COeQwzAxG1heuOPCHU2uizzBVg+MkyQLEpbFrvk=,tag:pbGgGPUTOVpjACbFQlno6g==,type:str]
kind: ENC[AES256_GCM,data:qpkuVgml,iv:wfhXRh9igWAnSLEPCGpsyKdw1Ciq4fSCKPc0uT74mGI=,tag:e6mqDQozQC7FBUMcd6gaWQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:s9gUFHnuOPzaZTpXpL5NUiwNyQ==,iv:uNmQvNWRcRtACsII+9SUWh/xj0CoH3oaT+NgCK+RR+s=,tag:Sgjh8MmW7G2AGgmDtM33JQ==,type:str]
  namespace: ENC[AES256_GCM,data:eGyJiFoJdlyIA+ni,iv:j12yQ8Jpx9RaVbLxDSrWRDdAy9HUHb5h7TYgFBHkgmg=,tag:/XalkqiGa4L9f6azq7xxSw==,type:str]
stringData:
  api-token: ENC[AES256_GCM,data:d1ZBl3dN5ZHJUP7QsjFATkkVfAVNWZFBJIHbthcz4iGOrM6igJ575A==,iv:i7cIhJlMQvc1npdL2I8jlFItxbe4dEFw3sRzg/jcb/s=,tag:OGafqg4MBTVyz0gQ1DbUaQ==,type:str]
sops:
  age:
    - recipient: age1pn9yaaq087hehhytd4kkjptah8zay6e3xehahzdl06h7rrx9kp5qj3z4wy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eEROTWhWeU9DRlgrWDM0
        cjlMbndpS3htcW9KSHg4dHRxd2JadVpMM0hJCmZDaEpQZHhzYmxpSHRwanlRbjdT
        eEhzbE5NZlErYzFiRWJZS3N0NVV4UjAKLS0tIGt0MjhpcmNQWXpKdDNmUlZJQXox
        S3RFR0E4dVNObUl6UGNreDFKM2wvTE0K2Fr+AB7QqlY00rTEG/n/KeCS06GF9m0U
        vAEUZh8rYWkx/7/cpywNNL7xce4uO2WGTRyt94lXgT5u4TXE8jRIrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-01T23:08:17Z"
  mac: ENC[AES256_GCM,data:jtsEo3UIj+E/VooXeyCo6XamoJFl9sucx0h9z4MWB3BnzSSld3SVtoZodKIGUzJfqW0HltapzvTmle3kwKQXDmv0ZHKUJGG32AF5QoJjWhOwlgUatZsteAbreNZLJBD9UU/8ovpIw/+Lm2en1wVdLI//B41PxlheobdQku+m04M=,iv:5Hbb8dMANwIQKHyaA1Jm5OM35QWQdEPuoucSdia1KY8=,tag:7qv1h/Tlp0BnvnJR3RiIfA==,type:str]
  unencrypted_suffix: _unencrypted
  mac_only_encrypted: true
  version: 3.10.2
