---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config-v1
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
