---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keda
  namespace: flux-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.17.2
  url: oci://ghcr.io/home-operations/charts-mirror/keda
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: observability
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: autoscaling
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: keda
      version: 2.12.1
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    operator:
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    metricsApiServer:
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    prometheus:
      metricServer:
        enabled: true
        port: 9022
        portName: metrics
      operator:
        enabled: true
        port: 8080
        portName: metrics

    serviceMonitor:
      metricServer:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s
      operator:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s

    webhooks:
      enabled: true
      certManager:
        enabled: true
