---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keda-operator-pdb
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keda-operator 