---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: 1.23.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    tempo:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

      retention: 24h
      reportingEnabled: false

      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces

      ingester:
        max_block_duration: 5m

      compactor:
        compaction:
          block_retention: 24h

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          interval: 30s
          scrapeTimeout: 10s

    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s

    service:
      ports:
        - name: otlp-grpc
          port: 4317
          protocol: TCP
          targetPort: 4317
        - name: otlp-http
          port: 4318
          protocol: TCP
          targetPort: 4318
        - name: tempo
          port: 3200
          protocol: TCP
          targetPort: 3200

    persistence:
      enabled: true
      size: 10Gi

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    ingress:
      enabled: true
      hosts:
        - host: tempo.local
          paths:
            - path: /
              pathType: Prefix