AWS_ACCESS_KEY_ID= op://K8s/aws/AWS_ACCESS_KEY_ID 
AWS_SECRET_ACCESS_KEY= op://K8s/aws/AWS_SECRET_ACCESS_KEY
IONOS_USERNAME= op://K8s/ionos/IONOS_USERNAME
IONOS_PASSWORD= op://K8s/ionos/IONOS_PASSWORD
IONOS_TOKEN= op://K8s/ionos/IONOS_TOKEN
IONOS_ENDPOINT= op://K8s/ionos/IONOS_ENDPOINT
OP_SERVICE_ACCOUNT_TOKEN= op://K8s/ionos/OP_SERVICE_ACCOUNT_TOKEN
