apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-secrets
  namespace: security
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wazuh-secrets
    template:
      engineVersion: v2
      data:
        WAZUH_CLUSTER_KEY: "{{ .cluster_key }}"
        WAZUH_AUTHD_PASS: "{{ .authd_pass }}"
        WAZUH_API_USER: "{{ .api_user }}"
        WAZUH_API_PASS: "{{ .api_pass }}"
        INDEXER_USER: "{{ .indexer_user }}"
        INDEXER_PASS: "{{ .indexer_pass }}"
        DASHBOARD_USER: "{{ .dashboard_user }}"
        DASHBOARD_PASS: "{{ .dashboard_pass }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        BACKUP_ENCRYPTION_KEY: "{{ .backup_encryption_key }}"
        OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
  data:
    - secretKey: cluster_key
      remoteRef:
        key: wazuh/cluster
        property: key
    - secretKey: authd_pass
      remoteRef:
        key: wazuh/auth
        property: password
    - secretKey: api_user
      remoteRef:
        key: wazuh/api
        property: username
    - secretKey: api_pass
      remoteRef:
        key: wazuh/api
        property: password
    - secretKey: indexer_user
      remoteRef:
        key: wazuh/indexer
        property: username
    - secretKey: indexer_pass
      remoteRef:
        key: wazuh/indexer
        property: password
    - secretKey: dashboard_user
      remoteRef:
        key: wazuh/dashboard
        property: username
    - secretKey: dashboard_pass
      remoteRef:
        key: wazuh/dashboard
        property: password
    - secretKey: encryption_key
      remoteRef:
        key: wazuh/encryption
        property: key
    - secretKey: backup_encryption_key
      remoteRef:
        key: wazuh/backup
        property: key
    - secretKey: oidc_client_id
      remoteRef:
        key: wazuh/oidc
        property: client_id
    - secretKey: oidc_client_secret
      remoteRef:
        key: wazuh/oidc
        property: client_secret