# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: observability
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-state-metrics
      version: 5.15.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    prometheus:
      monitor:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s
        honorLabels: true

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    collectors:
      - certificatesigningrequests
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - endpoints
      - horizontalpodautoscalers
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - replicasets
      - replicationcontrollers
      - resourcequotas
      - services
      - statefulsets
      - storageclasses

    metricLabelsAllowlist:
      - pods=[*]
      - nodes=[*]
      - persistentvolumeclaims=[*]
      - persistentvolumes=[*]

    metricAnnotationsAllowList:
      - pods=[*]

    kubeRBACProxy:
      enabled: false
