---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  - ./poddisruptionbudget.yaml

configMapGenerator:
  - name: reflector-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

labels:
  - pairs:
      app.kubernetes.io/name: reflector
      app.kubernetes.io/instance: reflector
      app.kubernetes.io/part-of: kube-system
      app.kubernetes.io/managed-by: flux
    includeSelectors: true
