---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy-redis
  namespace: security
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      oauth2-proxy-redis:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.0.2@sha256:1b835e5a8d5db58e8b718850bf43a68ef5a576fc68301fd08a789b20b4eecb61

            env:
              REDIS_REPLICATION_MODE: master

            envFrom:
              - secretRef:
                  name: oauth2-proxy-redis-secrets

            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi

    service:
      app:
        controller: oauth2-proxy-redis
        ports:
          redis:
            enabled: true
            port: 6379
