apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.76.1
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    mode: deployment

    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"

      processors:
        batch:
          timeout: 1s
          send_batch_size: 1024
        memory_limiter:
          check_interval: 1s
          limit_mib: 1024

      exporters:
        otlp:
          endpoint: tempo:4317
          tls:
            insecure: true
        prometheus:
          endpoint: "0.0.0.0:8889"

      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch, memory_limiter]
            exporters: [otlp]
          metrics:
            receivers: [otlp]
            processors: [batch, memory_limiter]
            exporters: [prometheus]

    ports:
      jaeger-compact:
        enabled: true
        containerPort: 6831
        servicePort: 6831
        hostPort: 6831
        protocol: UDP
      jaeger-grpc:
        enabled: true
        containerPort: 14250
        servicePort: 14250
        hostPort: 14250
      jaeger-thrift:
        enabled: true
        containerPort: 14268
        servicePort: 14268
        hostPort: 14268
      zipkin:
        enabled: true
        containerPort: 9411
        servicePort: 9411
        hostPort: 9411

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    serviceMonitor:
      enabled: true