name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: write
  checks: write
  deployments: write
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        # terraform_version: 0.13.0:
        cli_config_credentials_token: ${{ secrets.TOKEN }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      env:
        TF_VAR_ionos_access_key_id: ${{ secrets.IONOS_ACCESS_KEY_ID }}
        TF_VAR_ionos_secret_access_key: ${{ secrets.IONOS_SECRET_ACCESS_KEY }}
        TF_VAR_ionos_username: ${{ secrets.IONOS_USERNAME }}
        TF_VAR_ionos_password: ${{ secrets.IONOS_PASSWORD }}
        TF_VAR_ionos_datacenter_id: ${{ secrets.TOKEN }}

    - name: Terraform Get
      id: get
      run: terraform get

    - name: Terraform Init
      id: init
      run: terraform init -upgrade
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color -input=false
      continue-on-error: true

    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`
          </details>
          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      env:
        TOKEN: ${{ secrets.TOKEN }}
        TF_VAR_ionos_access_key_id: ${{ secrets.IONOS_ACCESS_KEY_ID }}
        TF_VAR_ionos_secret_access_key: ${{ secrets.IONOS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.ACTIONS }}
        PASSWORD: ${{ secrets.IONOS_PASSWORD }}
        USERNAME: ${{ secrets.IONOS_USERNAME }}