name: "Deploy Infrastructure"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths: ["infrastructure/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: write
  checks: write
  deployments: write

jobs:
  sync:
    name: Terraform Diff
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Install 1Password CLI (required for provider auth)
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v2

      # Configure 1Password (auth via service account token)
      - name: Configure 1Password
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false

      - name: Tofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: Tofu Init
        id: init
        run: tofu init

      - name: Tofu Validate
        id: validate
        run: tofu validate -no-color

      - name: Tofu Plan
        run: tofu plan -lock=false -out .planfile | grep -v "Refreshing state...\|Reading...\|Read complete after"

      - name: Post PR comment
        continue-on-error: true
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.TOKEN }}
          planfile: .planfile
          terraform-cmd: tofu
          header: "Terraform Plan for infrastructure"
          working-directory: infrastructure
