name: Deploy Infrastructure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: write
  checks: write
  deployments: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
        shell: bash
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v1

    - name: Load secrets from 1Password
      uses: 1password/load-secrets-action@v1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        TF_VAR_IONOS_USERNAME: "op://K8s/ionos/IONOS_USERNAME"
        TF_VAR_IONOS_PASSWORD: "op://K8s/ionos/IONOS_PASSWORD"
        TF_VAR_IONOS_ENDPOINT: "op://K8s/ionos/IONOS_ENDPOINT"
        AWS_ACCESS_KEY_ID: "op://K8s/ionos/AWS_ACCESS_KEY_ID"
        AWS_SECRET_ACCESS_KEY: "op://K8s/ionos/AWS_SECRET_ACCESS_KEY"
        TF_VAR_op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve