name: Deploy Infrastructure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: write
  checks: write
  deployments: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
        shell: bash
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v1

    - name: Load secrets from 1Password
      id: op-secrets
      uses: 1password/load-secrets-action@v1
      with:
        export_env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        # Define all secrets that need to be loaded
        IONOS_USERNAME: "op://K8s/ionos/IONOS_USERNAME"
        IONOS_PASSWORD: "op://K8s/ionos/IONOS_PASSWORD"
        IONOS_ENDPOINT: "op://K8s/ionos/IONOS_ENDPOINT"
        AWS_ACCESS_KEY_ID: "op://K8s/ionos/AWS_ACCESS_KEY_ID"
        AWS_SECRET_ACCESS_KEY: "op://K8s/ionos/AWS_SECRET_ACCESS_KEY"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: terraform init
      run: op run -- terraform init
      env:
        # Use the resolved values from 1Password
        IONOS_USERNAME: ${{ env.IONOS_USERNAME }}
        IONOS_PASSWORD: ${{ env.IONOS_PASSWORD }}
        IONOS_ENDPOINT: ${{ env.IONOS_ENDPOINT }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        # Pass as TF_VARs for Terraform variables
        TF_VAR_IONOS_USERNAME: ${{ env.IONOS_USERNAME }}
        TF_VAR_IONOS_PASSWORD: ${{ env.IONOS_PASSWORD }}
        TF_VAR_IONOS_ENDPOINT: ${{ env.IONOS_ENDPOINT }}
        TF_VAR_AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    - name: terraform plan
      run: op run -- terraform plan
      env:
        # Same environment variables as above
        IONOS_USERNAME: ${{ env.IONOS_USERNAME }}
        IONOS_PASSWORD: ${{ env.IONOS_PASSWORD }}
        IONOS_ENDPOINT: ${{ env.IONOS_ENDPOINT }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_IONOS_USERNAME: ${{ env.IONOS_USERNAME }}
        TF_VAR_IONOS_PASSWORD: ${{ env.IONOS_PASSWORD }}
        TF_VAR_IONOS_ENDPOINT: ${{ env.IONOS_ENDPOINT }}
        TF_VAR_AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: op run -- terraform apply -auto-approve
      env:
        # Same environment variables as above
        IONOS_USERNAME: ${{ env.IONOS_USERNAME }}
        IONOS_PASSWORD: ${{ env.IONOS_PASSWORD }}
        IONOS_ENDPOINT: ${{ env.IONOS_ENDPOINT }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_IONOS_USERNAME: ${{ env.IONOS_USERNAME }}
        TF_VAR_IONOS_PASSWORD: ${{ env.IONOS_PASSWORD }}
        TF_VAR_IONOS_ENDPOINT: ${{ env.IONOS_ENDPOINT }}
        TF_VAR_AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}