---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authelia
  namespace: security
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/gatus/guarded
  interval: 1h
  dependsOn:
    - name: cloudnative-pg
      namespace: storage
    - name: dragonfly
      namespace: storage
  path: ./kubernetes/apps/security/authelia/app
  postBuild:
    substitute:
      APP: auth
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  timeout: 5m
  wait: false
